# SPDX-FileCopyrightText: 2023 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-forgejo
    - install-all
    - install-forgejo

- block:
    - when: not forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-forgejo
