# SPDX-FileCopyrightText: 2023 MASH project contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Forgejo systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ forgejo_identifier }}.service"
  register: forgejo_service_stat

- name: Uninstall Forgejo systemd services and files
  when: forgejo_service_stat.stat.exists | bool
  block:
    - name: Ensure Forgejo systemd service is stopped
      ansible.builtin.service:
        name: "{{ forgejo_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Forgejo systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ forgejo_identifier }}.service"
        state: absent

    - name: Ensure Forgejo path does not exist
      ansible.builtin.file:
        path: "{{ forgejo_base_path }}"
        state: absent
